### ISSUE TITLE
packet storm problem

### ISSUE THREAD

**Issue by dmitryint** [Ulexus/docker-qemu-bootstrap#1]
Now it can run without this wrapper: `docker run --rm  --privileged --net=host --pid=host --ipc=host ulexus/qemu QEMU_OPTIONS`

**Comment by Ulexus** [comment]
Ah, thanks @dmitryint .  I had forgotten about this wrapper (though I'm still using it).  It makes sense that that would work.

**Comment by Ulexus** [comment]
`ulexus/qemu` no longer references this bootstrap
